build:
  environment:
    php: 7.1
    mysql: 5.7
    variables:
      APP_KEY: ''
      API_PREFIX: 'api'
      API_DEBUG: 'true'
    dependencies:
      after:
        command: php artisan key:generate
checks:
  php:
    code_rating: true
    duplication: true
    excluded_dependencies:
      - laravel/framework
filter:
  excluded_paths:
    - "config/"
    - "app/Console/"
    - "public/index.php"
    - "routes/console.php"
    - "database/seeds/"
    - "database/migrations/"
    - "vendor/"
