build:
  environment:
    php: 7.1
    mysql: 5.7
    variables:
      APP_KEY: 'base64:JCHiBK5X7wuGvFpsmh++TW8CBQLfGM4/VkQ2L9hZKJc='
      API_PREFIX: 'api'
      API_DEBUG: 'true'
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override: [php-scrutinizer-run]
checks:
  php:
    code_rating: true
    excluded_dependencies:
      - laravel/framework
filter:
  excluded_paths:
    - "config/"
    - "app/Console/"
    - "public/index.php"
    - "routes/console.php"
    - "database/seeds/"
    - "database/migrations/"
    - "vendor/"
